<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

subsetting = select  
indexing = select a specific element  
slicing = select a range of element  
masking = show only element that satisfies the masking criteria

# Exercise 2

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [6]:
number_array = np_array_2d[:,0]
number_array

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [11]:
intnumber_array = number_array.astype(int)
intnumber_array

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [13]:
rmnumber_array = intnumber_array%2
rmnumber_array

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [16]:
mask = rmnumber_array == 1
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [19]:
np_array_2d[mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [20]:
np_array_2d[mask][:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

QUESTION: is there any other ways (e.g. funciton to detect odd number) to make the code shorter?

*from tutor's comments:*  
(on loops)

In [2]:
testlist = [[1, "A"], [3, "C"], [2, "B"], [4, "D"], [5, "E"], [7, "G"], [6, "F"], [8, "H"], [10, "J"], [9, "I"]]
print([i[1] for i in testlist if i[0]%2==1])

['A', 'C', 'E', 'G', 'I']
